### ISSUE TITLE
Write the getting started documentation

### ISSUE THREAD

**Issue by Razoric480** [GDQuest/godot-steering-toolkit#5]
The quick-start documentation and user's guide needs to be written up to reach the MVP stage. The docstring for the classes could also use some improvement.

**Comment by NathanLovato** [comment]
Once François is done with that, @johnnygossdev, could you do the editing? Proofing and refining the text.

In general, let's work like that for writing: instead of doing review rounds, we can be more efficient working like professional writers. One writer, one or two editors.

In case you've not done it before:

1. The writer writes the content in one or two passes, until it's ready for review
2. Then hands it to the editor, who makes edits. Proofing, fixing typos, rephrasing. Here's an example: https://github.com/godotengine/godot-docs/commit/dcb9cb43e84defcdcfcd10a447cce665fb1ffb80
3. If any key information is missing, or requires the writer's expertise, the editor sends the document back for another loop.

It's simple, but also much more efficient than doing reviews as we do in code.

**Comment by johnnygossdev** [comment]
Yep not a problem! :+1:
